# -*- coding: utf-8 -*-
"""first_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B9IM_nQ8B6j4_WugKgGnrf5vJmiQ3k1n
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

spark = SparkSession.builder.appName("Test").getOrCreate()

path = "gs://gcp-bigquery-project1-bucket/data/test.csv"

df = spark.read.csv(path, header=True, inferSchema=True, sep=",")

df.columns

project_id = "gcp-bigquery-project1"
dataset_id = "first_test_flight_status"
table_id = "flight_status_table"

table_ref = f"{project_id}:{dataset_id}.{table_id}"

df.write \
  .format("bigquery") \
  .option("temporaryGcsBucket","gcp-bigquery-project1-bucket") \
  .option("table", table_ref) \
  .mode("overwrite") \
  .save()